import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from '../components/Header/Header'
import UserDetails from '../components/UserDetails/UserDetails'
import Avatar from '../components/Avatar/Avatar'
import Card from '../components/Card/Card'

const Home: NextPage = () => {
  return (
    <div className={styles.container + 'cover-whole-screen'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className={styles.profile}>
          <Avatar />
          <div className={styles.userDetails}>
            <UserDetails userInfoCategory={'Name'} userInfo={'Johnathan Buyers'} />
            <UserDetails userInfoCategory={'Email'} userInfo={'Johnathan Buyers'} />
            <UserDetails userInfoCategory={'Contact'} userInfo={'Johnathan Buyers'} />
          </div>
        </div>
        <h1>Your Configurations</h1>
        <div className={styles.grid}>
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </main>
    </div>
  )
}

export default Home
