import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

import Header from "../components/Header/Header";
import UserDetails from "../components/UserDetails/UserDetails";
import Avatar from "../components/Avatar/Avatar";
import Card from "../components/Card/Card";

import { UserDataType } from "../constants/UserDataType";

const Home: NextPage = () => {
  let [userData, setUserData] = useState<UserDataType | undefined>(undefined);
  if (userData == undefined) userData = {
    name: "",
    email: "",
    contact: "",
    configurationVideos: ['a', 'b', 'c', 'd']
  };
  const { query } = useRouter();

  useEffect(() => {
    const fetchData = async () => {
      try {
        const data = await fetch("https://api.metadome.ai/mgAutodome/63233107580f90fa24dbafa8", {
          method: "GET",
          redirect: "follow",
          mode:"no-cors"
        });
        console.log(data);
        const jsonData = await data.json();
        console.log(jsonData);
        // setUserData(jsonData.data);
      } catch (e) {
        console.log(e);
      }
    };

    fetchData();
    // fetch("https://api.metadome.ai/mgAutodome/63233107580f90fa24dbafa8", {
    //   method: "GET",
    //   redirect: "follow",
    //   mode: "no-cors"
    // })
    //   .then((response) => response.text())
    //   .then((actualData) => console.log(actualData))
    //   .catch((err) => {
    //     console.log(err.message);
    //   });
    }, []);

    // const userData: UserDataType = {
    //   name: "John",
    //   email: "jonathan@example.com",
    //   contact: "7999927777",
    //   configurationVideos: ['a', 'b', 'c', 'd']
    // };

    return (
      <div className={styles.container + "cover-whole-screen"}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Header />
          <div className="marginr5">
            <div className={styles.profile}>
              <Avatar imageSource={""} />
              {/* <UserDetails userInfoCategory={'Name'} userInfo={'Johnathan asda Buyers'} />
            <UserDetails userInfoCategory={'Email'} userInfo={'Johnathan sad Buyers'} />
            <UserDetails userInfoCategory={'Contact'} userInfo={'Johnathan sasaasdas Buyers'} /> */}
              <UserDetails userData={userData} />
            </div>
            <p className={styles.title}>Your Configurations</p>
            <div className={styles.grid}>
              {userData && userData.configurationVideos.map((element, index) => <Card key={index} videoSource={element} index={index + 1} />)}
            </div>
          </div>
        </main>
      </div>
    );
  };

  export default Home;
