import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Header from "../components/Header/Header";
import UserDetails from "../components/UserDetails/UserDetails";
import Avatar from "../components/Avatar/Avatar";
import Card from "../components/Card/Card";

import { UserDataType } from "../constants/UserDataType";

const Home: NextPage = () => {
  // let [userData, setUserData] = useState<UserDataType | null>(null);

  // const api = "";
  // useEffect(() => {
  //   const fetchData = async () => {
  //     const data = await fetch(api, {
  //       method: "GET"
  //     });
  //     const jsonData = await data.json();
  //     setUserData(jsonData.data);
  //   };

  //   fetchData();
  // }, [])

  const userData: UserDataType = {
    name: "John",
    email: "jonathan@example.com",
    contact: "7999927777",
    configurationVideos: ['a', 'b', 'c', 'd']
  };

  return (
    <div className={styles.container + "cover-whole-screen"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className="marginr5">
          <div className={styles.profile}>
            <Avatar imageSource={""} />
            {/* <UserDetails userInfoCategory={'Name'} userInfo={'Johnathan asda Buyers'} />
            <UserDetails userInfoCategory={'Email'} userInfo={'Johnathan sad Buyers'} />
            <UserDetails userInfoCategory={'Contact'} userInfo={'Johnathan sasaasdas Buyers'} /> */}
            <UserDetails {...userData} />
          </div>
          <p className={styles.title}>Your Configurations</p>
          <div className={styles.grid}>
            {userData.configurationVideos.map((element, index) => <Card key={index} videoSource={element} index={index + 1} />)}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
